blank_issues_enabled: false
contact_links:
  - name: Ozzy Website
    url: https://panda.hop.sh
    about: Ozzy Proxy 1.0
  - name: Heroku, Repl.it, Blocked site issues
    url: https://www.youtube.com/watch?v=BLUkgRAy_Vo
    about: Do not create issues for these.
